project:
  name: quickstart-sios-datakeeper
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-2
  - ap-southeast-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
general:
  s3_regional_buckets: true
  parameters:
      DomainAdminPassword: Password1
      KeyPairName: davmayd
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RDGWCIDR: 0.0.0.0/0
tests:
  ws2019-payg-nosql-sad-full:
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      AmiType: PAYG
      AvailabilityZones: $[taskcat_getaz_3]
      ClusterNodeOSServerVersion: WS2019
      SQLServerVersion: None
      SQLServiceAccountPassword: ''
      ThirdAZ: full
    regions:
    - us-east-1
    template: templates/sios-datakeeper-main.template