project:
  name: quickstart-sios-datakeeper
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-2
  - ap-southeast-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
general:
  s3_regional_buckets: true
  parameters:
      DomainAdminPassword: Password1
      KeyPairName: davmayd
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RDGWCIDR: 0.0.0.0/0
tests:
  ws2019-payg-nosql-sad:
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      AvailabilityZones: $[taskcat_getaz_3]
      ThirdAZ: full
      SQLServerVersion: None
    regions:
    - us-east-1
    template: templates/sios-datakeeper-main.template
  ws2019-payg-sql2017-mad:
    parameters:
      AvailabilityZones: $[taskcat_getaz_3]
      ThirdAZ: full
      SQLServiceAccountPassword: $[taskcat_genpass_16]
    regions:
    - eu-west-1
    template: templates/sios-datakeeper-main.template
  ws2016-payg-nosql-sad:
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      AvailabilityZones: $[taskcat_getaz_3]
      ClusterNodeOSServerVersion: WS2016
      ThirdAZ: witness
      SQLServerVersion: None
    regions:
    - us-east-2
    template: templates/sios-datakeeper-main.template
  ws2012r2-payg-nosql-mad:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      ClusterNodeOSServerVersion: WS2012R2
      SQLServerVersion: None
    regions:
    - us-west-1
    template: templates/sios-datakeeper-main.template
  ws2012r2-payg-sql2017-sad:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      ClusterNodeOSServerVersion: WS2012R2
      ThirdAZ: witness
      SQLServiceAccountPassword: $[taskcat_genpass_16]
    regions:
    - us-west-2
    template: templates/sios-datakeeper-main.template