project:
  name: quickstart-sios-datakeeper
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-2
  - ap-south-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
general:
  s3_regional_buckets: true
  parameters:
      DomainAdminPassword: Password1
      KeyPairName: davmayd
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RDGWCIDR: 0.0.0.0/0
tests:
  ws2012r2-payg-nosql-mad-none:
    template: templates/sios-datakeeper-main.template
    parameters:
      ADScenarioType: AWS Directory Service for Microsoft AD (Standard Edition)
      AmiType: PAYG
      AvailabilityZones: $[taskcat_getaz_2]
      ClusterNodeOSServerVersion: WS2012R2
      SQLServerVersion: None
      SQLServiceAccountPassword: ''
      ThirdAZ: none
    regions:
    - ap-south-1
  ws2016-payg-nosql-mad-witness:
    template: templates/sios-datakeeper-main.template
    parameters:
      ADScenarioType: AWS Directory Service for Microsoft AD (Standard Edition)
      AmiType: PAYG
      AvailabilityZones: $[taskcat_getaz_3]
      ClusterNodeOSServerVersion: WS2016
      SQLServerVersion: None
      SQLServiceAccountPassword: ''
      ThirdAZ: witness
    regions:
    - ap-southeast-2
  ws2012R2-payg-nosql-mad-full:
    template: templates/sios-datakeeper-main.template
    parameters:
      ADScenarioType: AWS Directory Service for Microsoft AD (Standard Edition)
      AmiType: PAYG
      AvailabilityZones: $[taskcat_getaz_3]
      ClusterNodeOSServerVersion: WS2012R2
      SQLServerVersion: None
      SQLServiceAccountPassword: ''
      ThirdAZ: full
    regions:
    - ca-central-1
  ws2019-payg-nosql-sad-none:
    template: templates/sios-datakeeper-main.template
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      AmiType: PAYG
      AvailabilityZones: $[taskcat_getaz_2]
      ClusterNodeOSServerVersion: WS2019
      SQLServerVersion: None
      SQLServiceAccountPassword: ''
      ThirdAZ: none
    regions:
    - eu-central-1
  ws2012r2-payg-nosql-sad-witness:
    template: templates/sios-datakeeper-main.template
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      AmiType: PAYG
      AvailabilityZones: $[taskcat_getaz_3]
      ClusterNodeOSServerVersion: WS2012R2
      SQLServerVersion: None
      SQLServiceAccountPassword: ''
      ThirdAZ: witness
    regions:
    - eu-west-1
  ws2016-payg-nosql-sad-full:
    template: templates/sios-datakeeper-main.template
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      AmiType: PAYG
      AvailabilityZones: $[taskcat_getaz_3]
      ClusterNodeOSServerVersion: WS2016
      SQLServerVersion: None
      SQLServiceAccountPassword: ''
      ThirdAZ: full
    regions:
    - eu-west-2
  ws2019-payg-sql2017-mad-none:
    template: templates/sios-datakeeper-main.template
    parameters:
      ADScenarioType: AWS Directory Service for Microsoft AD (Standard Edition)
      AmiType: PAYG
      AvailabilityZones: $[taskcat_getaz_2]
      ClusterNodeOSServerVersion: WS2019
      SQLServerVersion: 2017
      SQLServiceAccountPassword: $[taskcat_genpass_16]
      ThirdAZ: none
    regions:
    - eu-west-3
  ws2012R2-payg-sql2017-mad-witness:
    template: templates/sios-datakeeper-main.template
    parameters:
      ADScenarioType: AWS Directory Service for Microsoft AD (Standard Edition)
      AmiType: PAYG
      AvailabilityZones: $[taskcat_getaz_3]
      ClusterNodeOSServerVersion: WS2012R2
      SQLServerVersion: 2017
      SQLServiceAccountPassword: $[taskcat_genpass_16]
      ThirdAZ: witness
    regions:
    - sa-east-1
  ws2016-payg-sql2017-mad-full:
    template: templates/sios-datakeeper-main.template
    parameters:
      ADScenarioType: AWS Directory Service for Microsoft AD (Standard Edition)
      AmiType: PAYG
      AvailabilityZones: $[taskcat_getaz_3]
      ClusterNodeOSServerVersion: WS2016
      SQLServerVersion: 2017
      SQLServiceAccountPassword: $[taskcat_genpass_16]
      ThirdAZ: full
    regions:
    - us-east-1