project:
  name: quickstart-sios-datakeeper
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-2
  - ap-southeast-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  default:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      DomainAdminPassword: SIOS!5105?sios
      KeyPairName: davmayd
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RDGWCIDR: 0.0.0.0/0
      SQLServiceAccountPassword: $[taskcat_genpass_16]
    regions:
    - us-east-1
    template: templates/sios-datakeeper-main.template
