project:
  name: quickstart-sios-datakeeper
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-2
  - ap-south-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
general:
  s3_regional_buckets: true
  parameters:
      DomainAdminPassword: Password1
      KeyPairName: davmayd
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RDGWCIDR: 0.0.0.0/0
tests:
  ws2012r2-payg-nosql-mad-none:
    template: templates/sios-datakeeper-main.template.yaml
    parameters:
      ADScenarioType: AWS Directory Service for Microsoft AD (Standard Edition)
      AmiType: PAYG
      AvailabilityZones: $[taskcat_getaz_2]
      ClusterNodeOSServerVersion: WS2012R2
      SQLServerVersion: None
      SQLServiceAccountPassword: ''
      ThirdAZ: none
    regions:
    - ap-south-1